config/routes.rb
Rails.application.routes.draw do
  # NOTE: These routes from line 4-9 are being generated through line 25-27 with the resources, don't forget about DRY principle
  get "truck_stops/index"
  get "truck_stops/show"
  get "weigh_stations/index"
  get "weigh_stations/show"
  get "rest_areas/index"
  get "rest_areas/show"
  devise_for :drivers


  resources :loads do
    member do
      get   :preplan
      get   :plan, action: :preplan
      post  :add_stops
      delete :remove_stop
      post :start
      post :deliver
      post :drop
      post :regeocode
    end
  end
  resources :rest_areas,     only: [ :index, :show ]
  resources :weigh_stations, only: [ :index, :show ]
  resources :truck_stops,     only: [ :index, :show ]


  get "about", to: "pages#about"


  root "pages#home"
end

app/views/shared/_flash.html.erb
<%# NOTE: Not being used %>
<% if notice %><div style="padding:.5rem; background:#e8f5e9; margin:.5rem 0;"><%= notice %></div><% end %>
<% if alert  %><div style="padding:.5rem; background:#ffebee; margin:.5rem 0;"><%= alert  %></div><% end %>

app/views/shared/_navbar.html.erb
<%# NOTE: Not being used as well %>
<nav style="padding:.75rem 1rem; border-bottom:1px solid #eee;">
  <%= link_to "RigRadar", root_path %>
  <% if driver_signed_in? %>
    &nbsp; | <%= link_to "Loads", loads_path %>
    &nbsp; | <%= link_to "Rest Areas", rest_areas_path %>
    &nbsp; | <%= link_to "Weigh Stations", weigh_stations_path %>
    &nbsp; | <%= link_to "Account", edit_driver_registration_path %>
    &nbsp; | <%= button_to "Sign out", destroy_driver_session_path, method: :delete, form: { style: "display:inline" } %>
  <% else %>
    &nbsp; | <%= link_to "About", about_path rescue "#" %>
    &nbsp; | <%= link_to "Sign in",  new_driver_session_path %>
    &nbsp; | <%= link_to "Sign up",  new_driver_registration_path %>
  <% end %>
</nav>