config/routes.rb
Rails.application.routes.draw do
  # NOTE: These routes from line 4-9 are being generated through line 25-27 with the resources, don't forget about DRY principle
  get "truck_stops/index"
  get "truck_stops/show"
  get "weigh_stations/index"
  get "weigh_stations/show"
  get "rest_areas/index"
  get "rest_areas/show"
  devise_for :drivers


  resources :loads do
    member do
      get   :preplan
      get   :plan, action: :preplan
      post  :add_stops
      delete :remove_stop
      post :start
      post :deliver
      post :drop
      post :regeocode
    end
  end
  resources :rest_areas,     only: [ :index, :show ]
  resources :weigh_stations, only: [ :index, :show ]
  resources :truck_stops,     only: [ :index, :show ]


  get "about", to: "pages#about"


  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "RigRadar" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# NOTE: Be consistent on the spacing, make sure to ultilize rubocop %>
    <%# NOTE: For all the styling, we would like to see it in a CDN (content delivery network) partial, so you could include the bootstrap link and it's javascript tag as well. %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">

 
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

   
    <%= javascript_importmap_tags %>

 
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

   
    <%= yield :head %>
  </head>

  <body>
    <%# NOTE: Would like to see the navbar in it's own partial as well to keep the `application.html.erb` clean and neat, since the less code you have, the more readable it is. %>
    <nav class="navbar navbar-expand-lg navbar-rr">
      <div class="container">
        <%= link_to "RigRadar", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#rrNav"
          aria-controls="rrNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon" style="filter:invert(1);"></span>
        </button>

        <div class="collapse navbar-collapse" id="rrNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if driver_signed_in? %>
              <li class="nav-item"><%= link_to "Loads", loads_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Truck Stops", truck_stops_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Rest Areas", rest_areas_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Weigh Stations", weigh_stations_path, class: "nav-link" %></li>
            <% end %>
          </ul>

          <div class="d-flex gap-2">
            <% if driver_signed_in? %>
              <%= link_to "Account", edit_driver_registration_path, class: "btn btn-sm btn-outline-light" %>
              <%= button_to "Sign out", destroy_driver_session_path, method: :delete,
                    class: "btn btn-sm btn-light" %>
            <% else %>
              <%= link_to "Sign in", new_driver_session_path, class: "btn btn-sm btn-outline-light" %>
              <%= link_to "Get started", new_driver_registration_path, class: "btn btn-sm btn-light" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

   
    <%= yield :hero %>

    <%# NOTE: We noticed that you have `_flash.html.erb` in the shared, would love to see it being used, same for the `_navbar.html.erb` %>
    <div class="container mt-3">
      <% if notice.present? %>
        <div class="alert alert-success card-soft"><%= notice %></div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger card-soft"><%= alert %></div>
      <% end %>
    </div>

  
    <main class="container py-4">
      <%= yield %>
    </main>

   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"></script>
  </body>
</html>